
site_name: OtoshanDev

nav: 
  - privacy: privacy-policy.md


# ページのデザイン設定
theme:
  name: 'material'
  favicon: './images/favicon.ico'
  language: 'en'
  logo: './images/favicon.ico'
  palette:
    primary: grey
  font:
    text: 'Roboto'
    code: 'Roboto Mono'


copyright: Copyright©2020-2021 Otoshanapp. All Rights Reserved